In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [9]:
data = pd.read_csv('carprices.csv')

In [10]:
data.head()

Mileage  Age(yrs)  Sell Price($)
0    69000         6          18000
1    35000         3          34000
2    57000         5          26100
3    22500         2          40000
4    46000         4          31500

In [11]:
data.keys()

Index(['Mileage', 'Age(yrs)', 'Sell Price($)'], dtype='object')

In [12]:
data.Mileage

0     69000
1     35000
2     57000
3     22500
4     46000
5     59000
6     52000
7     72000
8     91000
9     67000
10    83000
11    79000
12    59000
13    58780
14    82450
15    25400
16    28000
17    69000
18    87600
19    52000
Name: Mileage, dtype: int64

In [14]:
Mileage = data["Mileage"].values.reshape(-1, 1)
Mileage

array([[69000],
       [35000],
       [57000],
       [22500],
       [46000],
       [59000],
       [52000],
       [72000],
       [91000],
       [67000],
       [83000],
       [79000],
       [59000],
       [58780],
       [82450],
       [25400],
       [28000],
       [69000],
       [87600],
       [52000]])

In [17]:
sellprice = data["Sell Price($)"].values.reshape(-1, 1)

In [18]:
sellprice

array([[18000],
       [34000],
       [26100],
       [40000],
       [31500],
       [26750],
       [32000],
       [19300],
       [12000],
       [22000],
       [18700],
       [19500],
       [26000],
       [27500],
       [19400],
       [35000],
       [35500],
       [19700],
       [12800],
       [28200]])

In [19]:
x,y = Mileage,sellprice

In [20]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

In [21]:
regressor = LinearRegression()

In [22]:
regressor.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [23]:
y_pred = regressor.predict(x_test)

In [25]:
y_pred[0]

array([15793.57937797])

In [26]:
y_test[0]

array([12800])

In [28]:
y_mean = np.mean(y_test)
y_mean

21750.0

In [29]:
rss = sum((y_test - y_pred)**2)
rss

array([15789147.7256289])

In [30]:
tss = sum((y_test -y_mean)**2)
tss

array([3.6683e+08])

In [31]:

r2_score = 1 - (rss / tss)
r2_score

array([0.95695786])